// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrekLxC_Pcb-Upi5xrvgpyFh0OhSuwxfY',
    appId: '1:215020353331:web:9790844d2d9f85c3b17046',
    messagingSenderId: '215020353331',
    projectId: 'sayurku-firebase',
    authDomain: 'sayurku-firebase.firebaseapp.com',
    storageBucket: 'sayurku-firebase.firebasestorage.app',
    measurementId: 'G-LNWX71ZBV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNUIV_zKqI7pADupMbTqlFm735PExRlGY',
    appId: '1:215020353331:android:e4042746a0ca0fd6b17046',
    messagingSenderId: '215020353331',
    projectId: 'sayurku-firebase',
    storageBucket: 'sayurku-firebase.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVrzx9WMKktMWP3bkAhNuDdHTmScgMN9k',
    appId: '1:215020353331:ios:ea6e7cea3aab0901b17046',
    messagingSenderId: '215020353331',
    projectId: 'sayurku-firebase',
    storageBucket: 'sayurku-firebase.firebasestorage.app',
    iosBundleId: 'com.example.sayurkuKelompok6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVrzx9WMKktMWP3bkAhNuDdHTmScgMN9k',
    appId: '1:215020353331:ios:ea6e7cea3aab0901b17046',
    messagingSenderId: '215020353331',
    projectId: 'sayurku-firebase',
    storageBucket: 'sayurku-firebase.firebasestorage.app',
    iosBundleId: 'com.example.sayurkuKelompok6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrekLxC_Pcb-Upi5xrvgpyFh0OhSuwxfY',
    appId: '1:215020353331:web:fedc0a873e7a9f02b17046',
    messagingSenderId: '215020353331',
    projectId: 'sayurku-firebase',
    authDomain: 'sayurku-firebase.firebaseapp.com',
    storageBucket: 'sayurku-firebase.firebasestorage.app',
    measurementId: 'G-C6BJ11EF5D',
  );
}
